// Build script: merges API logic + HTML template into _worker.js
const fs = require('fs');
const path = require('path');

const FRONTEND_DIR = path.join(__dirname, '..', 'frontend');

// Read HTML template
const html = fs.readFileSync(path.join(FRONTEND_DIR, 'page.html'), 'utf-8');

// Escape backticks and ${ in HTML for template literal
const escapedHtml = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

// API layer (kept identical to original)
const apiLayer = `// CIAS Frontend - Pages Worker (Proxy)
// Routes /api/* requests to Supabase REST API directly
// This bypasses the GFW-blocked workers.dev domain
// Auto-generated by scripts/build-worker.js - DO NOT EDIT MANUALLY

const SB_URL = "https://snycievdfcyoytthxspm.supabase.co";
const SB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueWNpZXZkZmN5b3l0dGh4c3BtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDI4MDEyOCwiZXhwIjoyMDk5ODU2MTI4fQ.NJGxkf_wb_VlSUDJ-YwCzXZ_98BfzzGa0goONcCLDYM";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...CORS_HEADERS },
  });
}

async function supabaseGet(table, query, select = "*") {
  const url = new URL(SB_URL + "/rest/v1/" + table);
  url.searchParams.set("select", select);
  for (const [key, value] of Object.entries(query)) {
    url.searchParams.set(key, value);
  }
  const resp = await fetch(url.toString(), {
    headers: {
      apikey: SB_KEY,
      Authorization: "Bearer " + SB_KEY,
    },
  });
  return resp.json();
}

async function supabasePost(table, body) {
  const resp = await fetch(SB_URL + "/rest/v1/" + table, {
    method: "POST",
    headers: {
      apikey: SB_KEY,
      Authorization: "Bearer " + SB_KEY,
      "Content-Type": "application/json",
      Prefer: "return=representation,resolution=merge-duplicates",
    },
    body: JSON.stringify(body),
  });
  return resp.json();
}

function getHTML() {
  return \`${escapedHtml}\`;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: CORS_HEADERS });
    }

    // API Routes
    if (path === "/api/health") {
      try {
        const data = await supabaseGet("match_facts", {}, "match_id");
        return jsonResponse({
          status: "healthy",
          database: Array.isArray(data) ? "ok" : "error",
          timestamp: new Date().toISOString(),
        });
      } catch (e) {
        return jsonResponse({ status: "error", database: "error", message: e.message });
      }
    }

    if (path === "/api/predictions") {
      const matchId = url.searchParams.get("matchId");
      if (!matchId) {
        return jsonResponse({ error: "matchId required" }, 400);
      }
      const data = await supabaseGet(
        "predictions",
        { match_id: "eq." + matchId, order: "created_at.desc", limit: "10" },
        "id,match_id,primary_result,primary_ft,primary_ht,hedge_result,hedge_ft,hedge_ht,direction_judgment,version_tag,is_lock,alignment_status,alignment_forced_degrade,key_factors,delta_explanation,created_at"
      );
      if (!data || data.length === 0) {
        return jsonResponse({ prediction: null });
      }
      const latest = data.find((p) => !p.is_archived) || data[0];
      return jsonResponse({ prediction: latest });
    }

    if (path === "/api/prediction") {
      const matchId = url.searchParams.get("matchId");
      if (!matchId) {
        return jsonResponse({ error: "matchId required" }, 400);
      }
      const data = await supabaseGet(
        "predictions",
        { match_id: "eq." + matchId, is_lock: "eq.true", order: "created_at.desc", limit: "1" },
        "id,match_id,primary_result,primary_ft,primary_ht,hedge_result,hedge_ft,hedge_ht,direction_judgment,version_tag,is_lock,alignment_status,alignment_forced_degrade,key_factors,delta_explanation,created_at"
      );
      if (!data || data.length === 0) {
        const fallback = await supabaseGet(
          "predictions",
          { match_id: "eq." + matchId, order: "created_at.desc", limit: "1" },
          "id,match_id,primary_result,primary_ft,primary_ht,hedge_result,hedge_ft,hedge_ht,direction_judgment,version_tag,is_lock,alignment_status,alignment_forced_degrade,key_factors,delta_explanation,created_at"
        );
        if (!fallback || fallback.length === 0) {
          return jsonResponse({ error: "No locked prediction found" }, 404);
        }
        return jsonResponse({ prediction: fallback[0] });
      }
      return jsonResponse({ prediction: data[0] });
    }

    if (path === "/api/all-predictions") {
      const data = await supabaseGet(
        "predictions",
        { is_archived: "eq.false", order: "created_at.desc", limit: "50" },
        "id,match_id,primary_result,primary_ft,primary_ht,hedge_result,hedge_ft,hedge_ht,direction_judgment,version_tag,is_lock,alignment_status,alignment_forced_degrade,key_factors,delta_explanation,created_at"
      );
      return jsonResponse({ predictions: data || [] });
    }

    if (path === "/api/match-facts") {
      const matchId = url.searchParams.get("matchId");
      if (!matchId) {
        return jsonResponse({ error: "matchId required" }, 400);
      }
      const data = await supabaseGet("match_facts", { match_id: "eq." + matchId }, "*");
      return jsonResponse({ facts: data[0] || null });
    }

    if (path === "/api/odds-snapshots") {
      const matchId = url.searchParams.get("matchId");
      if (!matchId) {
        return jsonResponse({ error: "matchId required" }, 400);
      }
      const data = await supabaseGet(
        "odds_snapshots",
        { match_id: "eq." + matchId, order: "captured_at.desc", limit: "10" },
        "id,match_id,captured_at,home_odds,draw_odds,away_odds,source,signal_type,is_sharp_move,is_steam_move"
      );
      return jsonResponse({ snapshots: data || [] });
    }

    if (path === "/api/reviews") {
      const limit = url.searchParams.get("limit") || "20";
      const matchId = url.searchParams.get("matchId");
      const query = { order: "created_at.desc", limit };
      if (matchId) { query.match_id = "eq." + matchId; }
      const data = await supabaseGet(
        "review_results",
        query,
        "id,match_id,prediction_id,actual_result,actual_ft,actual_ht,attribution_code,attribution_party,attribution_detail,error_type,is_upset,created_at"
      );
      return jsonResponse({ reviews: data || [] });
    }

    if (path === "/api/config") {
      const key = url.searchParams.get("key") || "factor_weights";
      const data = await supabaseGet("system_config", { key: "eq." + key }, "key,value");
      return jsonResponse({ key, value: data[0] ? data[0].value : {} });
    }

    if (path === "/api/config/betting-window") {
      if (request.method === "GET") {
        const data = await supabaseGet("system_config", { key: "eq.betting_window_config" }, "key,value");
        return jsonResponse({ config: data[0] ? data[0].value : {} });
      }
      if (request.method === "POST") {
        try {
          const body = await request.json();
          const start = body.start_hours_before_kickoff;
          const end = body.end_minutes_before_kickoff;
          const fundDelay = body.fundamentals_delay_after_start_hours;
          const finalLock = body.final_lock_minutes_before_end;
          const league_ids = body.league_ids;
          const season = body.season;
          if (typeof start !== "number" || start < 1 || start > 72) {
            return jsonResponse({ error: "start_hours_before_kickoff must be 1-72" }, 400);
          }
          if (typeof end !== "number" || end < 0 || end > 120) {
            return jsonResponse({ error: "end_minutes_before_kickoff must be 0-120" }, 400);
          }
          if (end >= start * 60) {
            return jsonResponse({ error: "end must be less than start * 60" }, 400);
          }
          const cfg = {
            start_hours_before_kickoff: start,
            end_minutes_before_kickoff: end,
            fundamentals_delay_after_start_hours: typeof fundDelay === "number" ? fundDelay : 0.5,
            final_lock_minutes_before_end: typeof finalLock === "number" ? finalLock : 15,
            api_football_league_ids: Array.isArray(league_ids) ? league_ids : [39, 140, 135, 78, 61],
            target_leagues: ["soccer_epl", "soccer_spain_la_liga", "soccer_italy_serie_a", "soccer_germany_bundesliga", "soccer_france_ligue_one"],
            season: typeof season === "string" ? season : "2025",
          };
          const result = await supabasePost("system_config", { key: "betting_window_config", value: cfg });
          return jsonResponse({ success: true, config: cfg, result });
        } catch (e) {
          return jsonResponse({ error: e.message }, 500);
        }
      }
    }

    if (path === "/api/upcoming-matches") {
      const data = await supabaseGet(
        "matches",
        { status: "eq.scheduled", order: "kickoff_time.asc", limit: "20" },
        "match_id,home_team,away_team,league,kickoff_time,status,round,venue"
      );
      return jsonResponse({ matches: data || [] });
    }

    if (path === "/api/all-match-facts") {
      const data = await supabaseGet(
        "match_facts",
        { order: "match_id.asc" },
        "match_id,home_xg_adj,away_xg_adj,home_conc_adj,away_conc_adj,injury_impact_home,injury_impact_away,weather_decay,referee_strictness,motivation_home,motivation_away,odds_zone,bias_correction,data_confidence,status,created_at"
      );
      return jsonResponse({ matches: data || [] });
    }

    // Serve HTML for root and non-API paths
    if (path === "/" || path === "/index.html" || !path.startsWith("/api/")) {
      const html = getHTML();
      return new Response(html, {
        headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "public, max-age=0, must-revalidate" },
      });
    }

    return jsonResponse({ error: "Not found" }, 404);
  },
};
`;

fs.writeFileSync(path.join(FRONTEND_DIR, '_worker.js'), apiLayer);
console.log('Built _worker.js successfully (' + apiLayer.length + ' bytes)');
